pipeline:
  identifier: Build_anujs2099_python_1705762921789
  name: Build python
  orgIdentifier: default
  projectIdentifier: chapter1ci
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1705762806302
        repoName: anujs2099/python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_python_app
                  name: Build Python App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      python -m pip install --upgrade pip
                      pip install  pytest
                      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
